export const ActionTypes = {
    SET_ALL_MATCHED_MOVIES: "SET_ALL_MATCHED_MOVIES",
    ADD_MOVIE_TO_WATCH_LATER: "ADD_MOVIE_TO_WATCH_LATER",
    REMOVE_MOVIE_FROM_WATCH_LATER: "REMOVE_MOVIE_FROM_WATCH_LATER",
};